

data = [
  { "id": 350, "name": "", "name_tag": "Công ty Unitec", "id_sector": 4 },
  { "id": 212, "name": "A101", "name_tag": "", "id_sector": 1 },
  { "id": 213, "name": "A102", "name_tag": "", "id_sector": 1 },
  { "id": 214, "name": "A103", "name_tag": "", "id_sector": 1 },
  { "id": 215, "name": "A104", "name_tag": "", "id_sector": 1 },
  { "id": 216, "name": "A105", "name_tag": "", "id_sector": 1 },
  { "id": 217, "name": "A106", "name_tag": "", "id_sector": 1 },
  { "id": 218, "name": "A107", "name_tag": "", "id_sector": 1 },
  { "id": 219, "name": "A108", "name_tag": "", "id_sector": 1 },
  { "id": 220, "name": "A109", "name_tag": "", "id_sector": 1 },
  { "id": 221, "name": "A110", "name_tag": "", "id_sector": 1 },
  { "id": 222, "name": "A111", "name_tag": "", "id_sector": 1 },
  { "id": 223, "name": "A112", "name_tag": "", "id_sector": 1 },
  { "id": 224, "name": "A113", "name_tag": "", "id_sector": 1 },
  { "id": 225, "name": "A114", "name_tag": "", "id_sector": 1 },
  { "id": 226, "name": "A115", "name_tag": "", "id_sector": 1 },
  { "id": 227, "name": "A116", "name_tag": "", "id_sector": 1 },
  { "id": 228, "name": "A117", "name_tag": "", "id_sector": 1 },
  { "id": 229, "name": "A118A", "name_tag": "", "id_sector": 1 },
  { "id": 311, "name": "A118B", "name_tag": "", "id_sector": 1 },
  { "id": 230, "name": "A119", "name_tag": "", "id_sector": 1 },
  { "id": 231, "name": "A120", "name_tag": "", "id_sector": 1 },
  { "id": 232, "name": "A121", "name_tag": "", "id_sector": 1 },
  { "id": 233, "name": "A122", "name_tag": "", "id_sector": 1 },
  { "id": 310, "name": "A122B", "name_tag": "", "id_sector": 1 },
  { "id": 234, "name": "A123", "name_tag": "", "id_sector": 1 },
  { "id": 149, "name": "A124", "name_tag": "", "id_sector": 1 },
  { "id": 235, "name": "A125", "name_tag": "", "id_sector": 1 },
  { "id": 312, "name": "A125B", "name_tag": "", "id_sector": 1 },
  { "id": 236, "name": "A126A", "name_tag": "", "id_sector": 1 },
  { "id": 313, "name": "A126B", "name_tag": "", "id_sector": 1 },
  { "id": 150, "name": "A127", "name_tag": "", "id_sector": 1 },
  { "id": 237, "name": "A128", "name_tag": "", "id_sector": 1 },
  { "id": 151, "name": "A129", "name_tag": "", "id_sector": 1 },
  { "id": 238, "name": "A130", "name_tag": "", "id_sector": 1 },
  { "id": 239, "name": "A131", "name_tag": "", "id_sector": 1 },
  { "id": 240, "name": "A132", "name_tag": "", "id_sector": 1 },
  { "id": 1, "name": "A133A", "name_tag": "", "id_sector": 1 },
  { "id": 2, "name": "A133B", "name_tag": "", "id_sector": 1 },
  { "id": 3, "name": "A134", "name_tag": "", "id_sector": 1 },
  { "id": 241, "name": "A135", "name_tag": "", "id_sector": 1 },
  { "id": 4, "name": "A136", "name_tag": "", "id_sector": 1 },
  { "id": 242, "name": "A137", "name_tag": "", "id_sector": 1 },
  { "id": 243, "name": "A138", "name_tag": "", "id_sector": 1 },
  { "id": 244, "name": "A139", "name_tag": "", "id_sector": 1 },
  { "id": 245, "name": "A140", "name_tag": "", "id_sector": 1 },
  { "id": 5, "name": "A141", "name_tag": "", "id_sector": 1 },
  { "id": 6, "name": "A142", "name_tag": "", "id_sector": 1 },
  { "id": 246, "name": "A143", "name_tag": "", "id_sector": 1 },
  { "id": 7, "name": "A144", "name_tag": "", "id_sector": 1 },
  { "id": 8, "name": "A145A", "name_tag": "", "id_sector": 1 },
  { "id": 9, "name": "A145B", "name_tag": "", "id_sector": 1 },
  { "id": 247, "name": "A146", "name_tag": "", "id_sector": 1 },
  { "id": 248, "name": "A147", "name_tag": "", "id_sector": 1 },
  { "id": 249, "name": "A148", "name_tag": "", "id_sector": 1 },
  { "id": 250, "name": "A149", "name_tag": "", "id_sector": 1 },
  { "id": 251, "name": "A150", "name_tag": "", "id_sector": 1 },
  { "id": 252, "name": "A151", "name_tag": "", "id_sector": 1 },
  { "id": 253, "name": "A152", "name_tag": "", "id_sector": 1 },
  { "id": 254, "name": "A153", "name_tag": "", "id_sector": 1 },
  { "id": 152, "name": "A154", "name_tag": "", "id_sector": 1 },
  { "id": 255, "name": "A155", "name_tag": "", "id_sector": 1 },
  { "id": 256, "name": "A201", "name_tag": "", "id_sector": 1 },
  { "id": 257, "name": "A202", "name_tag": "", "id_sector": 1 },
  { "id": 258, "name": "A203", "name_tag": "", "id_sector": 1 },
  { "id": 259, "name": "A204", "name_tag": "", "id_sector": 1 },
  { "id": 260, "name": "A205", "name_tag": "", "id_sector": 1 },
  { "id": 261, "name": "A206", "name_tag": "", "id_sector": 1 },
  { "id": 262, "name": "A207", "name_tag": "", "id_sector": 1 },
  { "id": 263, "name": "A208", "name_tag": "", "id_sector": 1 },
  { "id": 264, "name": "A209", "name_tag": "", "id_sector": 1 },
  { "id": 265, "name": "A210", "name_tag": "", "id_sector": 1 },
  { "id": 266, "name": "A211", "name_tag": "", "id_sector": 1 },
  { "id": 267, "name": "A212", "name_tag": "", "id_sector": 1 },
  { "id": 268, "name": "A213-214", "name_tag": "", "id_sector": 1 },
  { "id": 269, "name": "A215", "name_tag": "", "id_sector": 1 },
  { "id": 270, "name": "A216", "name_tag": "", "id_sector": 1 },
  { "id": 271, "name": "A217", "name_tag": "", "id_sector": 1 },
  { "id": 272, "name": "A218", "name_tag": "", "id_sector": 1 },
  { "id": 273, "name": "A219", "name_tag": "", "id_sector": 1 },
  { "id": 274, "name": "A220", "name_tag": "", "id_sector": 1 },
  { "id": 275, "name": "A221", "name_tag": "", "id_sector": 1 },
  { "id": 276, "name": "A222", "name_tag": "", "id_sector": 1 },
  { "id": 277, "name": "A223", "name_tag": "", "id_sector": 1 },
  { "id": 278, "name": "A224a", "name_tag": "", "id_sector": 1 },
  { "id": 314, "name": "A224b", "name_tag": "", "id_sector": 1 },
  { "id": 279, "name": "A225", "name_tag": "", "id_sector": 1 },
  { "id": 280, "name": "A226", "name_tag": "", "id_sector": 1 },
  { "id": 281, "name": "A227", "name_tag": "", "id_sector": 1 },
  { "id": 282, "name": "A228", "name_tag": "", "id_sector": 1 },
  { "id": 283, "name": "A229", "name_tag": "", "id_sector": 1 },
  { "id": 284, "name": "A230", "name_tag": "", "id_sector": 1 },
  { "id": 285, "name": "A231", "name_tag": "", "id_sector": 1 },
  { "id": 286, "name": "A301a", "name_tag": "", "id_sector": 1 },
  { "id": 315, "name": "A301b", "name_tag": "", "id_sector": 1 },
  { "id": 287, "name": "A302", "name_tag": "", "id_sector": 1 },
  { "id": 288, "name": "A303a", "name_tag": "", "id_sector": 1 },
  { "id": 316, "name": "A303b", "name_tag": "", "id_sector": 1 },
  { "id": 289, "name": "A304", "name_tag": "", "id_sector": 1 },
  { "id": 317, "name": "A304b", "name_tag": "", "id_sector": 1 },
  { "id": 153, "name": "A305", "name_tag": "", "id_sector": 1 },
  { "id": 290, "name": "A306", "name_tag": "", "id_sector": 1 },
  { "id": 291, "name": "A307", "name_tag": "", "id_sector": 1 },
  { "id": 292, "name": "A308", "name_tag": "", "id_sector": 1 },
  { "id": 293, "name": "A309", "name_tag": "", "id_sector": 1 },
  { "id": 294, "name": "A310", "name_tag": "", "id_sector": 1 },
  { "id": 295, "name": "A311", "name_tag": "", "id_sector": 1 },
  { "id": 296, "name": "A312", "name_tag": "", "id_sector": 1 },
  { "id": 297, "name": "A313", "name_tag": "", "id_sector": 1 },
  { "id": 298, "name": "A314", "name_tag": "", "id_sector": 1 },
  { "id": 299, "name": "A315", "name_tag": "", "id_sector": 1 },
  { "id": 300, "name": "A316", "name_tag": "", "id_sector": 1 },
  { "id": 301, "name": "A317", "name_tag": "", "id_sector": 1 },
  { "id": 302, "name": "A318", "name_tag": "", "id_sector": 1 },
  { "id": 303, "name": "A319", "name_tag": "", "id_sector": 1 },
  { "id": 304, "name": "A320", "name_tag": "", "id_sector": 1 },
  { "id": 305, "name": "A321", "name_tag": "", "id_sector": 1 },
  { "id": 306, "name": "A322", "name_tag": "", "id_sector": 1 },
  { "id": 307, "name": "A323", "name_tag": "", "id_sector": 1 },
  { "id": 308, "name": "A401a", "name_tag": "", "id_sector": 1 },
  { "id": 309, "name": "A401b", "name_tag": "", "id_sector": 1 },
  { "id": 154, "name": "AVL1", "name_tag": "", "id_sector": "2" },
  { "id": 155, "name": "AVL2", "name_tag": "", "id_sector": "2" },
  { "id": 10, "name": "B101", "name_tag": "", "id_sector": 3 },
  { "id": 11, "name": "B102", "name_tag": "", "id_sector": 3 },
  { "id": 12, "name": "B104", "name_tag": "", "id_sector": 3 },
  { "id": 13, "name": "B105", "name_tag": "", "id_sector": 3 },
  { "id": 14, "name": "B106", "name_tag": "", "id_sector": 3 },
  { "id": 15, "name": "B108", "name_tag": "", "id_sector": 3 },
  { "id": 16, "name": "B109", "name_tag": "", "id_sector": 3 },
  { "id": 17, "name": "B201", "name_tag": "", "id_sector": 3 },
  { "id": 18, "name": "B202", "name_tag": "", "id_sector": 3 },
  { "id": 19, "name": "B204", "name_tag": "", "id_sector": 3 },
  { "id": 20, "name": "B205", "name_tag": "", "id_sector": 3 },
  { "id": 21, "name": "B206", "name_tag": "", "id_sector": 3 },
  { "id": 22, "name": "B207", "name_tag": "", "id_sector": 3 },
  { "id": 23, "name": "B208", "name_tag": "", "id_sector": 3 },
  { "id": 24, "name": "B209", "name_tag": "", "id_sector": 3 },
  { "id": 25, "name": "B301", "name_tag": "", "id_sector": 3 },
  { "id": 26, "name": "B302", "name_tag": "", "id_sector": 3 },
  { "id": 27, "name": "B303", "name_tag": "", "id_sector": 3 },
  { "id": 28, "name": "B304", "name_tag": "", "id_sector": 3 },
  { "id": 29, "name": "B305", "name_tag": "", "id_sector": 3 },
  {
    "id": 30,
    "name": "C101",
    "name_tag": "Phòng máy tính",
    "id_sector": 4
  },
  {
    "id": 31,
    "name": "C102-103",
    "name_tag": "Phòng máy tính",
    "id_sector": 4
  },
  {
    "id": 319,
    "name": "C104",
    "name_tag": "PTN Hệ thống nhúng",
    "id_sector": 4
  },
  {
    "id": 32,
    "name": "C105",
    "name_tag": "Phòng máy tính",
    "id_sector": 4
  },
  {
    "id": 318,
    "name": "C106",
    "name_tag": "VP TT Tin học",
    "id_sector": 4
  },
  {
    "id": 33,
    "name": "C107",
    "name_tag": "Phòng TN Cisco",
    "id_sector": 4
  },
  { "id": 320, "name": "C108", "name_tag": "Văn phòng", "id_sector": 4 },
  {
    "id": 321,
    "name": "C109",
    "name_tag": "Phòng trưởng khoa",
    "id_sector": 4
  },
  {
    "id": 322,
    "name": "C110",
    "name_tag": "BM k.thuật điện tử",
    "id_sector": 4
  },
  {
    "id": 323,
    "name": "C111",
    "name_tag": "BM k.thuật viễn thông",
    "id_sector": 4
  },
  {
    "id": 324,
    "name": "C112",
    "name_tag": "Phòng thiết bị",
    "id_sector": 4
  },
  { "id": 34, "name": "C113", "name_tag": "Phòng học", "id_sector": 4 },
  { "id": 35, "name": "C114", "name_tag": "Phòng học", "id_sector": 4 },
  {
    "id": 325,
    "name": "C115",
    "name_tag": "Phòng Điện tử đại cương & Hệ thống nhúng",
    "id_sector": 4
  },
  {
    "id": 326,
    "name": "C115b",
    "name_tag": "Phòng Thí Nghiệm",
    "id_sector": 4
  },
  {
    "id": 327,
    "name": "C116a",
    "name_tag": "PTN Viễn thông",
    "id_sector": 4
  },
  {
    "id": 328,
    "name": "C116b",
    "name_tag": "PTN Viễn thông",
    "id_sector": 4
  },
  { "id": 36, "name": "C117", "name_tag": "Phòng học", "id_sector": 4 },
  { "id": 329, "name": "C118", "name_tag": "PTN mô phỏng", "id_sector": 4 },
  {
    "id": 330,
    "name": "C119",
    "name_tag": "Phòng làm việc CLB Pioneer",
    "id_sector": 4
  },
  {
    "id": 156,
    "name": "C120",
    "name_tag": "PTN Điện tử 1",
    "id_sector": 4
  },
  {
    "id": 37,
    "name": "C121",
    "name_tag": "Xưởng Điện tử ",
    "id_sector": 4
  },
  {
    "id": 157,
    "name": "C121B",
    "name_tag": "PTN Điện tử 2",
    "id_sector": 4
  },
  {
    "id": 331,
    "name": "C122",
    "name_tag": "Kho lưu trữ đồ án, tài liệu liên quan",
    "id_sector": 4
  },
  {
    "id": 332,
    "name": "C123",
    "name_tag": "Phòng họp khoa",
    "id_sector": 4
  },
  {
    "id": 333,
    "name": "C124",
    "name_tag": "Văn thu Giáo vụ",
    "id_sector": 4
  },
  {
    "id": 334,
    "name": "C125",
    "name_tag": "Bộ môn Mạng - máy tính",
    "id_sector": 4
  },
  {
    "id": 335,
    "name": "C126",
    "name_tag": "Bộ môn Công nghệ phần mềm",
    "id_sector": 4
  },
  {
    "id": 336,
    "name": "C127",
    "name_tag": "Bộ môn hệ thống nhúng",
    "id_sector": 4
  },
  {
    "id": 337,
    "name": "C128",
    "name_tag": "Phòng máy tính chuyên đề 1",
    "id_sector": 4
  },
  {
    "id": 158,
    "name": "C201",
    "name_tag": "Phòng máy tính",
    "id_sector": 4
  },
  {
    "id": 159,
    "name": "C202",
    "name_tag": "Phòng máy tính",
    "id_sector": 4
  },
  {
    "id": 338,
    "name": "C203",
    "name_tag": "Phòng máy tính",
    "id_sector": 4
  },
  {
    "id": 160,
    "name": "C204",
    "name_tag": "Phòng máy tính",
    "id_sector": 4
  },
  {
    "id": 161,
    "name": "C205",
    "name_tag": "Phòng máy tính",
    "id_sector": 4
  },
  {
    "id": 162,
    "name": "C206-207",
    "name_tag": "Phòng máy tính",
    "id_sector": 4
  },
  {
    "id": 339,
    "name": "C208",
    "name_tag": "Bộ môn kỹ thuật máy tính",
    "id_sector": 4
  },
  { "id": 344, "name": "C208a", "name_tag": "Phó khoa", "id_sector": 4 },
  { "id": 345, "name": "C208b", "name_tag": "Phó khoa", "id_sector": 4 },
  {
    "id": 163,
    "name": "C209",
    "name_tag": "Phòng máy tính",
    "id_sector": 4
  },
  {
    "id": 340,
    "name": "C210",
    "name_tag": "Phòng làm việc",
    "id_sector": 4
  },
  { "id": 341, "name": "C211", "name_tag": "Phòng họp", "id_sector": 4 },
  {
    "id": 342,
    "name": "C212",
    "name_tag": "Phòng Giáo vụ",
    "id_sector": 4
  },
  {
    "id": 343,
    "name": "C213",
    "name_tag": "PTN Vi điện tử & Thiết kế IC",
    "id_sector": 4
  },
  { "id": 38, "name": "C213B", "name_tag": "Phòng học", "id_sector": 4 },
  {
    "id": 348,
    "name": "C214",
    "name_tag": "Phòng Giáo sư",
    "id_sector": 4
  },
  { "id": 39, "name": "C215", "name_tag": "Phòng Server", "id_sector": 4 },
  { "id": 349, "name": "C216", "name_tag": "Phòng DLS", "id_sector": 4 },
  {
    "id": 346,
    "name": "C217",
    "name_tag": "PTN Robotics & Capstone Project",
    "id_sector": 4
  },
  {
    "id": 347,
    "name": "C218",
    "name_tag": "Phòng nước giáo viên",
    "id_sector": 4
  },
  { "id": 40, "name": "C219", "name_tag": "Phòng học", "id_sector": 4 },
  {
    "id": 351,
    "name": "C220",
    "name_tag": "Phòng làm việc",
    "id_sector": 4
  },
  {
    "id": 352,
    "name": "C221",
    "name_tag": "PTN Đo lường điện tử",
    "id_sector": 4
  },
  { "id": 353, "name": "C222", "name_tag": "Phòng tự học", "id_sector": 4 },
  {
    "id": 354,
    "name": "C223",
    "name_tag": "Phòng thư viện",
    "id_sector": 4
  },
  {
    "id": 355,
    "name": "C224",
    "name_tag": "Bộ môn ô tô và máy công trình",
    "id_sector": 4
  },
  {
    "id": 356,
    "name": "C225",
    "name_tag": "Bộ môn máy động lực",
    "id_sector": 4
  },
  {
    "id": 357,
    "name": "C226",
    "name_tag": "Bộ môn thủy khí & máy thủy khí",
    "id_sector": 4
  },
  {
    "id": 358,
    "name": "C227",
    "name_tag": "Phòng trưởng khoa",
    "id_sector": 4
  },
  {
    "id": 359,
    "name": "C229",
    "name_tag": "Văn phòng khoa Phòng họp",
    "id_sector": 4
  },
  {
    "id": 362,
    "name": "C229",
    "name_tag": "Phòng trưởng khoa",
    "id_sector": 4
  },
  {
    "id": 360,
    "name": "C230",
    "name_tag": "Phòng Giáo vụ",
    "id_sector": 4
  },
  { "id": 361, "name": "C231", "name_tag": "PTN Datic", "id_sector": 4 },
  { "id": 41, "name": "C301", "name_tag": "Phòng học", "id_sector": 4 },
  { "id": 42, "name": "C302", "name_tag": "Phòng học", "id_sector": 4 },
  { "id": 43, "name": "C303", "name_tag": "Phòng học", "id_sector": 4 },
  {
    "id": 44,
    "name": "C304",
    "name_tag": "Văn phòng Đoàn",
    "id_sector": 4
  },
  { "id": 164, "name": "D103", "name_tag": "", "id_sector": 5 },
  { "id": 165, "name": "D105", "name_tag": "", "id_sector": 5 },
  { "id": 166, "name": "D106", "name_tag": "", "id_sector": 5 },
  { "id": 167, "name": "D109", "name_tag": "", "id_sector": 5 },
  { "id": 168, "name": "D111", "name_tag": "", "id_sector": 5 },
  { "id": 169, "name": "D112", "name_tag": "", "id_sector": 5 },
  { "id": 170, "name": "D116", "name_tag": "", "id_sector": 5 },
  { "id": 171, "name": "D205", "name_tag": "", "id_sector": 5 },
  { "id": 172, "name": "D207", "name_tag": "", "id_sector": 5 },
  { "id": 173, "name": "D210", "name_tag": "", "id_sector": 5 },
  { "id": 174, "name": "D215", "name_tag": "", "id_sector": 5 },
  { "id": 175, "name": "E111.", "name_tag": "", "id_sector": 6 },
  { "id": 45, "name": "E101", "name_tag": "", "id_sector": 6 },
  { "id": 46, "name": "E102", "name_tag": "", "id_sector": 6 },
  { "id": 47, "name": "E103", "name_tag": "", "id_sector": 6 },
  { "id": 48, "name": "E104", "name_tag": "", "id_sector": 6 },
  { "id": 49, "name": "E110A", "name_tag": "", "id_sector": 6 },
  { "id": 50, "name": "E110B", "name_tag": "", "id_sector": 6 },
  { "id": 51, "name": "E112", "name_tag": "", "id_sector": 6 },
  { "id": 52, "name": "E113", "name_tag": "", "id_sector": 6 },
  { "id": 53, "name": "E114", "name_tag": "", "id_sector": 6 },
  { "id": 54, "name": "E201A", "name_tag": "", "id_sector": 6 },
  { "id": 55, "name": "E201B", "name_tag": "", "id_sector": 6 },
  { "id": 56, "name": "E202A", "name_tag": "", "id_sector": 6 },
  { "id": 57, "name": "E202B", "name_tag": "", "id_sector": 6 },
  { "id": 58, "name": "E203", "name_tag": "", "id_sector": 6 },
  { "id": 59, "name": "E204A", "name_tag": "", "id_sector": 6 },
  { "id": 60, "name": "E204B", "name_tag": "", "id_sector": 6 },
  { "id": 61, "name": "E205", "name_tag": "", "id_sector": 6 },
  { "id": 62, "name": "E206", "name_tag": "", "id_sector": 6 },
  { "id": 63, "name": "E207", "name_tag": "", "id_sector": 6 },
  { "id": 64, "name": "E208", "name_tag": "", "id_sector": 6 },
  { "id": 65, "name": "E209", "name_tag": "", "id_sector": 6 },
  { "id": 66, "name": "E210", "name_tag": "", "id_sector": 6 },
  { "id": 67, "name": "E301A", "name_tag": "", "id_sector": 6 },
  { "id": 68, "name": "E301B", "name_tag": "", "id_sector": 6 },
  { "id": 69, "name": "E302", "name_tag": "", "id_sector": 6 },
  { "id": 70, "name": "E303", "name_tag": "", "id_sector": 6 },
  { "id": 71, "name": "E304", "name_tag": "", "id_sector": 6 },
  { "id": 72, "name": "E305", "name_tag": "", "id_sector": 6 },
  { "id": 73, "name": "E401", "name_tag": "", "id_sector": 6 },
  { "id": 74, "name": "E402", "name_tag": "", "id_sector": 6 },
  { "id": 75, "name": "E403", "name_tag": "", "id_sector": 6 },
  { "id": 76, "name": "E404", "name_tag": "", "id_sector": 6 },
  { "id": 77, "name": "E405", "name_tag": "", "id_sector": 6 },
  { "id": 78, "name": "E406", "name_tag": "", "id_sector": 6 },
  { "id": 79, "name": "F101", "name_tag": "", "id_sector": 7 },
  { "id": 80, "name": "F102", "name_tag": "", "id_sector": 7 },
  { "id": 81, "name": "F103", "name_tag": "", "id_sector": 7 },
  { "id": 176, "name": "F104", "name_tag": "", "id_sector": 7 },
  { "id": 177, "name": "F105", "name_tag": "", "id_sector": 7 },
  { "id": 82, "name": "F106", "name_tag": "", "id_sector": 7 },
  { "id": 83, "name": "F107", "name_tag": "", "id_sector": 7 },
  { "id": 84, "name": "F108", "name_tag": "", "id_sector": 7 },
  { "id": 85, "name": "F109", "name_tag": "", "id_sector": 7 },
  { "id": 86, "name": "F110", "name_tag": "", "id_sector": 7 },
  { "id": 87, "name": "F201", "name_tag": "", "id_sector": 7 },
  { "id": 88, "name": "F202", "name_tag": "", "id_sector": 7 },
  { "id": 89, "name": "F203", "name_tag": "", "id_sector": 7 },
  { "id": 178, "name": "F204", "name_tag": "", "id_sector": 7 },
  { "id": 179, "name": "F205", "name_tag": "", "id_sector": 7 },
  { "id": 90, "name": "F206", "name_tag": "", "id_sector": 7 },
  { "id": 91, "name": "F207", "name_tag": "", "id_sector": 7 },
  { "id": 92, "name": "F208", "name_tag": "", "id_sector": 7 },
  { "id": 93, "name": "F209", "name_tag": "", "id_sector": 7 },
  { "id": 94, "name": "F210", "name_tag": "", "id_sector": 7 },
  { "id": 95, "name": "F301", "name_tag": "", "id_sector": 7 },
  { "id": 96, "name": "F302", "name_tag": "", "id_sector": 7 },
  { "id": 97, "name": "F303", "name_tag": "", "id_sector": 7 },
  { "id": 180, "name": "F304", "name_tag": "", "id_sector": 7 },
  { "id": 181, "name": "F305", "name_tag": "", "id_sector": 7 },
  { "id": 98, "name": "F306", "name_tag": "", "id_sector": 7 },
  { "id": 99, "name": "F307", "name_tag": "", "id_sector": 7 },
  { "id": 100, "name": "F308", "name_tag": "", "id_sector": 7 },
  { "id": 101, "name": "F309", "name_tag": "", "id_sector": 7 },
  { "id": 102, "name": "F310", "name_tag": "", "id_sector": 7 },
  { "id": 103, "name": "F401", "name_tag": "", "id_sector": 7 },
  { "id": 104, "name": "F402", "name_tag": "", "id_sector": 7 },
  { "id": 105, "name": "F403", "name_tag": "", "id_sector": 7 },
  { "id": 106, "name": "F404", "name_tag": "", "id_sector": 7 },
  { "id": 107, "name": "F405", "name_tag": "", "id_sector": 7 },
  { "id": 108, "name": "F406", "name_tag": "", "id_sector": 7 },
  { "id": 109, "name": "F407", "name_tag": "", "id_sector": 7 },
  { "id": 110, "name": "F408", "name_tag": "", "id_sector": 7 },
  { "id": 111, "name": "F409", "name_tag": "", "id_sector": 7 },
  {
    "id": 182,
    "name": "G101A",
    "name_tag": "PTN vật liệu xây dựng 1",
    "id_sector": 8
  },
  {
    "id": 366,
    "name": "G101B",
    "name_tag": "PTN Vật liệu xây dựng 2",
    "id_sector": 8
  },
  {
    "id": 183,
    "name": "G102",
    "name_tag": "PTN cầu đường",
    "id_sector": 8
  },
  {
    "id": 367,
    "name": "G103",
    "name_tag": "Thiết bị thanh lý",
    "id_sector": 8
  },
  { "id": 184, "name": "G105", "name_tag": "Project name", "id_sector": 8 },
  { "id": 185, "name": "G106", "name_tag": "PTN Thủy lực", "id_sector": 8 },
  {
    "id": 186,
    "name": "G201",
    "name_tag": "PTN địa kỹ thuật",
    "id_sector": 8
  },
  {
    "id": 363,
    "name": "G202",
    "name_tag": "Phòng thiết bị tính năng cao",
    "id_sector": 8
  },
  {
    "id": 364,
    "name": "G203",
    "name_tag": "Phòng máy tính + tự học",
    "id_sector": 8
  },
  {
    "id": 365,
    "name": "G204",
    "name_tag": "Phòng máy trắc địa",
    "id_sector": 8
  },
  { "id": 187, "name": "G206", "name_tag": "", "id_sector": 8 },
  { "id": 112, "name": "H101", "name_tag": "", "id_sector": 9 },
  { "id": 113, "name": "H102", "name_tag": "", "id_sector": 9 },
  { "id": 114, "name": "H103", "name_tag": "", "id_sector": 9 },
  { "id": 115, "name": "H104", "name_tag": "", "id_sector": 9 },
  { "id": 116, "name": "H105", "name_tag": "", "id_sector": 9 },
  { "id": 117, "name": "H106", "name_tag": "", "id_sector": 9 },
  { "id": 118, "name": "H107", "name_tag": "", "id_sector": 9 },
  { "id": 119, "name": "H108", "name_tag": "", "id_sector": 9 },
  { "id": 120, "name": "H201", "name_tag": "", "id_sector": 9 },
  { "id": 121, "name": "H202", "name_tag": "", "id_sector": 9 },
  { "id": 122, "name": "H203", "name_tag": "", "id_sector": 9 },
  { "id": 123, "name": "H204", "name_tag": "", "id_sector": 9 },
  { "id": 124, "name": "H205", "name_tag": "", "id_sector": 9 },
  { "id": 125, "name": "H206", "name_tag": "", "id_sector": 9 },
  { "id": 126, "name": "H207", "name_tag": "", "id_sector": 9 },
  { "id": 127, "name": "H208", "name_tag": "", "id_sector": 9 },
  { "id": 128, "name": "H301", "name_tag": "", "id_sector": 9 },
  { "id": 129, "name": "H302", "name_tag": "", "id_sector": 9 },
  { "id": 130, "name": "H303", "name_tag": "", "id_sector": 9 },
  { "id": 131, "name": "H304", "name_tag": "", "id_sector": 9 },
  { "id": 132, "name": "H305", "name_tag": "", "id_sector": 9 },
  { "id": 133, "name": "H306", "name_tag": "", "id_sector": 9 },
  { "id": 134, "name": "H307", "name_tag": "", "id_sector": 9 },
  { "id": 135, "name": "H308", "name_tag": "", "id_sector": 9 },
  { "id": 136, "name": "H401", "name_tag": "", "id_sector": 9 },
  { "id": 137, "name": "H402", "name_tag": "", "id_sector": 9 },
  { "id": 138, "name": "HL301", "name_tag": "", "id_sector": 10 },
  { "id": 139, "name": "HL302", "name_tag": "", "id_sector": 10 },
  { "id": 140, "name": "HL305", "name_tag": "", "id_sector": 10 },
  { "id": 188, "name": "I103", "name_tag": "", "id_sector": 11 },
  { "id": 189, "name": "I104", "name_tag": "", "id_sector": 11 },
  { "id": 190, "name": "I105", "name_tag": "", "id_sector": 11 },
  { "id": 191, "name": "I202", "name_tag": "", "id_sector": 11 },
  { "id": 192, "name": "I203", "name_tag": "", "id_sector": 11 },
  { "id": 193, "name": "I304", "name_tag": "", "id_sector": 11 },
  { "id": 194, "name": "I305", "name_tag": "", "id_sector": 11 },
  { "id": 195, "name": "K101", "name_tag": "", "id_sector": 12 },
  { "id": 196, "name": "K105", "name_tag": "", "id_sector": 12 },
  { "id": 197, "name": "K107", "name_tag": "", "id_sector": 12 },
  { "id": 198, "name": "M201", "name_tag": "", "id_sector": 13 },
  { "id": 199, "name": "M202", "name_tag": "", "id_sector": 13 },
  { "id": 200, "name": "M204", "name_tag": "", "id_sector": 13 },
  { "id": 201, "name": "M206", "name_tag": "", "id_sector": 13 },
  { "id": 202, "name": "NM" },
  { "id": 141, "name": "P1", "name_tag": "", "id_sector": 14 },
  { "id": 142, "name": "P2", "name_tag": "", "id_sector": 14 },
  { "id": 143, "name": "P3", "name_tag": "", "id_sector": 14 },
  { "id": 144, "name": "P4", "name_tag": "", "id_sector": 14 },
  { "id": 145, "name": "P5", "name_tag": "", "id_sector": 14 },
  { "id": 146, "name": "P6", "name_tag": "", "id_sector": 14 },
  { "id": 147, "name": "P7", "name_tag": "", "id_sector": 14 },
  { "id": 203, "name": "PTN", "name_tag": "", "id_sector": null },
  { "id": 204, "name": "PTN 2", "name_tag": "", "id_sector": null },
  { "id": 205, "name": "PTNA", "name_tag": "", "id_sector": null },
  { "id": 206, "name": "PTNB", "name_tag": "", "id_sector": null },
  { "id": 148, "name": "PV", "name_tag": "", "id_sector": 14 },
  { "id": 207, "name": "SVĐ", "name_tag": "", "id_sector": null },
  { "id": 208, "name": "X", "name_tag": "", "id_sector": null },
  { "id": 209, "name": "XP", "name_tag": "", "id_sector": null },
  { "id": 210, "name": "Xưởng CK", "name_tag": "", "id_sector": null },
  { "id": 211, "name": "Xưởng ĐL", "name_tag": "", "id_sector": null }
];